global:
  ingress:
    enabled: false
    className: ''
    host: app.glimnote.dev
    tls: []
  secret:
    secretName: 'server-private-key'
    privateKey: ''
  database:
    user: 'affine_owner'
    url: 'ep-ancient-frost-a1t1enyk.ap-southeast-1.aws.neon.tech'
    port: '5432'
    name: 'affine?sslmode=require'
    password: ''
    gcloud:
      enabled: false
      # use for migration
      cloudSqlInternal: ''
      connectionName: ''
      serviceAccount: ''
      cloudProxyReplicas: 3
      proxyPort: '5432'
  redis:
    enabled: true
    host: '35.234.27.79'
    port: '6379'
    username: 'default'
    password: ''
    database: 0
  gke:
    enabled: true

graphql:
  service:
    type: ClusterIP
    port: 3000
    annotations:
      cloud.google.com/backend-config: '{"default": "affine-backendconfig"}'

sync:
  service:
    type: ClusterIP
    port: 3010
    annotations:
      cloud.google.com/backend-config: '{"default": "affine-backendconfig"}'

web:
  service:
    type: ClusterIP
    port: 8080
